<?php

namespace BlogBundle\Entity\Repositories;

/**
 * ReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplyRepository extends \Doctrine\ORM\EntityRepository
{
}
